---
language: python
python: "2.7"

sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible==2.3.1.0

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

before_script:
  # Create test user
  - sudo useradd --create-home user

script:
  # Basic role syntax check
  - ansible-playbook --syntax-check --inventory-file=tests/inventory tests/all-tests.yml

  # Test template expansion
  - ansible-playbook --inventory-file=tests/inventory tests/test-template.yml

  # Test deposition
  - ansible-playbook --inventory-file=tests/inventory tests/test-deposition.yml

  # Idempotence test
  - >
    ansible-playbook --inventory-file=tests/inventory tests/test-deposition.yml \
      | grep --quiet 'changed=0.*failed=0' \
        && (echo 'Idempotence test: pass' && exit 0) \
        || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
